import json
from pathlib import Path

from meta_harness.waste import CORRECTION_RE, Stretch, iter_stretches


def write_transcript(tmp_path: Path, records: list[dict]) -> Path:
    path = tmp_path / "session.jsonl"
    with path.open("w", encoding="utf-8") as handle:
        for record in records:
            handle.write(json.dumps(record) + "\n")
    return path


def assistant(*tools):
    content = [{"type": "tool_use", "id": f"t{i}", "name": n, "input": inp}
               for i, (n, inp) in enumerate(tools)]
    return {"type": "assistant", "message": {"role": "assistant", "content": content}}


def user(text):
    return {"type": "user", "message": {"role": "user", "content": text}}


def test_a_run_of_tool_calls_between_user_messages_is_one_stretch(tmp_path):
    path = write_transcript(tmp_path, [
        user("add a flag"),
        assistant(("Read", {"file_path": "a.py"}), ("Edit", {"file_path": "a.py"})),
        assistant(("Bash", {"command": "pytest"})),
        user("thanks"),
    ])
    stretches = list(iter_stretches(path, min_calls=3))
    assert len(stretches) == 1
    assert stretches[0].calls == ["Read", "Edit", "Bash"]
    assert stretches[0].ended_by == "user"


def test_a_correction_is_labelled_and_carries_its_text(tmp_path):
    path = write_transcript(tmp_path, [
        user("add a flag"),
        assistant(("Read", {"file_path": "a.py"}), ("Edit", {"file_path": "a.py"}),
                  ("Bash", {"command": "pytest"})),
        user("no, that's not what I asked for"),
    ])
    stretch = next(iter_stretches(path, min_calls=3))
    assert stretch.ended_by == "correction"
    assert "not what I asked" in stretch.correction_text


def test_short_stretches_are_not_yielded(tmp_path):
    path = write_transcript(tmp_path, [
        user("hi"), assistant(("Read", {"file_path": "a.py"})), user("no, wrong"),
    ])
    assert list(iter_stretches(path, min_calls=3)) == []


def test_paths_are_collected_from_tool_input(tmp_path):
    path = write_transcript(tmp_path, [
        user("go"),
        assistant(("Read", {"file_path": "src/a.py"}), ("Edit", {"file_path": "src/b.py"}),
                  ("Bash", {"command": "ls src"})),
        user("ok"),
    ])
    stretch = next(iter_stretches(path, min_calls=3))
    assert "src/a.py" in stretch.paths and "src/b.py" in stretch.paths


def test_one_malformed_line_does_not_abort_the_file(tmp_path):
    path = tmp_path / "session.jsonl"
    good = [user("go"),
            assistant(("Read", {"file_path": "a"}), ("Edit", {"file_path": "b"}),
                      ("Bash", {"command": "c"})),
            user("no, wrong")]
    with path.open("w", encoding="utf-8") as handle:
        handle.write(json.dumps(good[0]) + "\n")
        handle.write('{"type": "assistant", "message": {"content": [trunc\n')  # truncated write
        handle.write(json.dumps(good[1]) + "\n")
        handle.write(json.dumps(good[2]) + "\n")
    stretch = next(iter_stretches(path, min_calls=3))
    assert stretch.ended_by == "correction"


def test_a_missing_file_yields_nothing_rather_than_raising(tmp_path):
    assert list(iter_stretches(tmp_path / "absent.jsonl")) == []


# --- fix round 1: harness-injected user text is not the human speaking -----------------------
#
# These fixtures copy the exact shape of real records found under ~/.claude/projects, rather
# than an invented approximation: a <task-notification> is a plain string message.content
# (not a list of blocks), and "[Request interrupted by user]" is a one-block list with a
# "text" field - both shapes are exercised below.

TASK_NOTIFICATION = (
    "<task-notification>\n<task-id>w8fezmhrt</task-id>\n"
    "<tool-use-id>toolu_01MDU8ZNDqC6rs4CpZvZ2pft</tool-use-id>\n"
    "<status>stopped</status>\n<summary>No completion record was found for background "
    'workflow "erp-scout-phase1" from the previous session. It may have been stopped (via '
    "the UI or TaskStop) or it may have been running when the previous Claude Code process "
    "exited.</summary>\n</task-notification>"
)

SLASH_COMMAND_ECHO = (
    "<command-name>/config</command-name>\n            "
    "<command-message>config</command-message>\n            <command-args></command-args>"
)

LOCAL_COMMAND_STDOUT = (
    "<local-command-stdout>Set verbose to true\nSet output style to Explanatory"
    "</local-command-stdout>"
)

LOCAL_COMMAND_CAVEAT = (
    "<local-command-caveat>Caveat: The messages below were generated by the user while "
    "running local commands. DO NOT respond to these messages or otherwise consider them in "
    "your response unless the user explicitly asks you to.</local-command-caveat>"
)

SYSTEM_REMINDER = (
    "<system-reminder>\nYour final report is delivered through SubagentHandback: when your "
    "work is complete, call SubagentHandback(...) and then stop.\n</system-reminder>"
)


def interrupted_notice():
    """The real shape: a one-block content list with a "text" field, not a bare string."""
    return {"type": "user", "message": {"role": "user",
            "content": [{"type": "text", "text": "[Request interrupted by user]"}]}}


def test_a_task_notification_reporting_stopped_does_not_end_or_correct_the_stretch(tmp_path):
    path = write_transcript(tmp_path, [
        user("go"),
        assistant(("Read", {"file_path": "a.py"}), ("Edit", {"file_path": "a.py"})),
        user(TASK_NOTIFICATION),
        assistant(("Bash", {"command": "pytest"})),
        user("thanks"),
    ])
    stretches = list(iter_stretches(path, min_calls=3))
    assert len(stretches) == 1
    assert stretches[0].calls == ["Read", "Edit", "Bash"]
    assert stretches[0].ended_by == "user"


def test_slash_command_echo_and_local_command_scaffolding_do_not_end_a_stretch(tmp_path):
    path = write_transcript(tmp_path, [
        user("go"),
        assistant(("Read", {"file_path": "a.py"})),
        user(SLASH_COMMAND_ECHO),
        assistant(("Edit", {"file_path": "a.py"})),
        user(LOCAL_COMMAND_STDOUT),
        user(LOCAL_COMMAND_CAVEAT),
        assistant(("Bash", {"command": "pytest"})),
        user("looks good"),
    ])
    stretches = list(iter_stretches(path, min_calls=3))
    assert len(stretches) == 1
    assert stretches[0].calls == ["Read", "Edit", "Bash"]


def test_system_reminder_and_interrupt_notice_do_not_end_a_stretch(tmp_path):
    path = write_transcript(tmp_path, [
        user("go"),
        assistant(("Read", {"file_path": "a.py"}), ("Edit", {"file_path": "a.py"})),
        user(SYSTEM_REMINDER),
        interrupted_notice(),
        assistant(("Bash", {"command": "pytest"})),
        user("no, wrong"),
    ])
    stretch = next(iter_stretches(path, min_calls=3))
    assert stretch.calls == ["Read", "Edit", "Bash"]
    assert stretch.ended_by == "correction"


def test_correction_regex_does_not_match_stop_inside_stopped():
    assert CORRECTION_RE.search("<status>stopped</status>") is None
    assert CORRECTION_RE.search("no, stop that") is not None


def test_correction_regex_still_matches_bare_no_comma_and_actually_comma():
    assert CORRECTION_RE.search("no, that's wrong") is not None
    assert CORRECTION_RE.search("actually, revert that") is not None


# --- fix round 1: _paths_in must not collect SHA ranges or URL fragments as paths ------------

def test_paths_reject_git_sha_ranges_and_url_fragments(tmp_path):
    path = write_transcript(tmp_path, [
        user("go"),
        assistant(("Bash", {"command": "git diff 145181b..HEAD -- src/a.py"}),
                  ("Bash", {"command": "curl https://github.com/foo/bar.git"}),
                  ("Read", {"file_path": "src/a.py"})),
        user("ok"),
    ])
    stretch = next(iter_stretches(path, min_calls=3))
    assert "src/a.py" in stretch.paths
    assert not any(".." in p for p in stretch.paths)
    assert not any("://" in p or p.startswith("//") for p in stretch.paths)


# --- fix round 2: the correction detector is precision-tuned against a gold set, not intuition -

IDE_OPENED_FILE = "<ide_opened_file>\nThe user opened src/a.py in the IDE.\n</ide_opened_file>"

# Synthetic fixtures below, shaped like the reviewer's three false-positive patterns, but
# invented text, never a real transcript's message.

PASTED_REPORT_THEN_NEW_REQUEST = (
    "<pasted_content>Summary: this was wrong, we should revert and instead do it the other "
    "way.</pasted_content> Also please add a dark mode toggle to the settings page."
)

OPERATIONAL_STOP_SERVER = "stop the dev server, then start it again on port 4000"
OPERATIONAL_STOP_AGENTS = "please stop all the background agents now"

# The trigger word is many sentences past the opening - ordinary steering deep in a longer
# message, not a leading objection.
BURIED_TRIGGER = (
    "Let's add a new export button to the dashboard. It should download a CSV. Put it next to "
    "the filter row. Users have been asking for this for a while. Actually, on second thought, "
    "maybe a menu item instead of a button would be cleaner here, up to you."
)

LEADING_REVERT_DEEP_IN_A_LONG_MESSAGE = (
    "Please revert the last change - it broke the build. " + ("padding text. " * 200)
)

REVERT_MENTIONED_ONLY_FAR_INTO_A_VERY_LONG_MESSAGE = (
    ("unrelated filler text. " * 500) + "by the way somewhere a changelog mentions a revert"
)


def test_ide_opened_file_marker_does_not_end_a_stretch(tmp_path):
    path = write_transcript(tmp_path, [
        user("go"),
        assistant(("Read", {"file_path": "a.py"}), ("Edit", {"file_path": "a.py"})),
        user(IDE_OPENED_FILE),
        assistant(("Bash", {"command": "pytest"})),
        user("thanks"),
    ])
    stretches = list(iter_stretches(path, min_calls=3))
    assert len(stretches) == 1
    assert stretches[0].calls == ["Read", "Edit", "Bash"]


def test_pasted_report_ahead_of_a_new_request_is_not_a_correction(tmp_path):
    path = write_transcript(tmp_path, [
        user("go"),
        assistant(("Read", {"file_path": "a.py"}), ("Edit", {"file_path": "a.py"}),
                  ("Bash", {"command": "pytest"})),
        user(PASTED_REPORT_THEN_NEW_REQUEST),
    ])
    stretch = next(iter_stretches(path, min_calls=3))
    assert stretch.ended_by == "user"


def test_operational_stop_instructions_are_not_corrections(tmp_path):
    for text in (OPERATIONAL_STOP_SERVER, OPERATIONAL_STOP_AGENTS):
        path = write_transcript(tmp_path, [
            user("go"),
            assistant(("Read", {"file_path": "a.py"}), ("Edit", {"file_path": "a.py"}),
                      ("Bash", {"command": "pytest"})),
            user(text),
        ])
        stretch = next(iter_stretches(path, min_calls=3))
        assert stretch.ended_by == "user", text


def test_a_trigger_word_buried_deep_in_a_longer_message_is_not_a_correction(tmp_path):
    path = write_transcript(tmp_path, [
        user("go"),
        assistant(("Read", {"file_path": "a.py"}), ("Edit", {"file_path": "a.py"}),
                  ("Bash", {"command": "pytest"})),
        user(BURIED_TRIGGER),
    ])
    stretch = next(iter_stretches(path, min_calls=3))
    assert stretch.ended_by == "user"


def test_revert_deep_in_a_long_message_still_counts_as_a_correction(tmp_path):
    path = write_transcript(tmp_path, [
        user("go"),
        assistant(("Read", {"file_path": "a.py"}), ("Edit", {"file_path": "a.py"}),
                  ("Bash", {"command": "pytest"})),
        user(LEADING_REVERT_DEEP_IN_A_LONG_MESSAGE),
    ])
    stretch = next(iter_stretches(path, min_calls=3))
    assert stretch.ended_by == "correction"


def test_revert_far_beyond_the_fulltext_scan_cap_is_not_a_correction(tmp_path):
    path = write_transcript(tmp_path, [
        user("go"),
        assistant(("Read", {"file_path": "a.py"}), ("Edit", {"file_path": "a.py"}),
                  ("Bash", {"command": "pytest"})),
        user(REVERT_MENTIONED_ONLY_FAR_INTO_A_VERY_LONG_MESSAGE),
    ])
    stretch = next(iter_stretches(path, min_calls=3))
    assert stretch.ended_by == "user"
